#!/bin/bash
echo "============================================"
echo "  EXECUCAO EM TERMINAIS SEPARADOS"
echo "  Luiz Athar, Pedro Rossi, Samuel Mauli"
echo "============================================"
echo ""
echo "Execute cada comando em um terminal diferente:"
echo ""
echo "  Terminal 1 (Fabrica):"
echo "    java -cp bin fabrica.FabricaMain"
echo ""
echo "  Terminal 2 (Loja 1):"
echo "    java -cp bin loja.LojaMain 1"
echo ""
echo "  Terminal 3 (Loja 2):"
echo "    java -cp bin loja.LojaMain 2"
echo ""
echo "  Terminal 4 (Loja 3):"
echo "    java -cp bin loja.LojaMain 3"
echo ""
echo "  Terminal 5 (Clientes):"
echo "    java -cp bin cliente.ClienteMain"
echo ""
echo "IMPORTANTE: Inicie na ordem acima!"
echo "============================================"
